bsm powermeter
EVerest/everest-core pull request #134
Opened 2022-11-02 09:12 UTC by chrkli22

- implements powermeter interface, including "get_signed_meter_value", which returns a signed OCMF snapshot string.
- publishes variable "powermeter" of type Powermeter.
- type Powermeter: added optional VAR property.
- cmd for requesting standard sunspec ac meter model.
- uses SerialCommHub or direct modbus.

Module currently runs without problems on its testinstallation.

Branch will be squashed when this pull request is accepted.

2022-11-03 09:06 UTC, a-w50 requested changes
- source files missing copyright
- include guards quite short (ifdef collision)
- multiline comments deprecated
- look at codacy issues
- namespaces should be lowercase
- base_types / known_models / sunspec_* / driver_base belong into libmodbus/libsunspec
- only transport and BSM... will stay, for these you wouldn't need all this cmake extra stuff if you add them directly as sources to the module

2022-11-03 09:06 UTC, a-w50 commented on modules/PowermeterBSM/lib/sunspec_base.hpp
> +static std::string pointTypeToString(PointType pointType) {
casing

2022-11-03 09:06 UTC, a-w50 commented on modules/PowermeterBSM/lib/sunspec_base.hpp
> +constexpr std::uint16_t point_length_in_bytes(PointType pointType) {
casing

2022-11-03 09:06 UTC, a-w50 commented on modules/PowermeterBSM/lib/sunspec_base.hpp
> +    PointType pointType;
casing

2022-11-03 09:06 UTC, a-w50 commented on modules/PowermeterBSM/lib/sunspec_base.hpp
> +    return be16toh((*reinterpret_cast<const std::uint16_t*>(std::addressof(data.data()[offset]))));
what about (data.data() + offset) instead of std::addressof(data.data()[offset])?

2022-11-04 13:09 UTC, chrkli22 commented
> * source files missing copyright
fixed.

> * include guards quite short (ifdef collision)
never seen this happen, changed that anyway.

> * multiline comments deprecated
Hu? Who deprecated, and why?

> * look at codacy issues
> * namespaces should be lowercase
fixed.

> * base_types / known_models / sunspec_* / driver_base belong into libmodbus/libsunspec
No, libsunspec is not used here. 

> * only transport and BSM... will stay, for these you wouldn't need all this cmake extra stuff if you add them directly as sources to the module

shortened that cmake stuff a bit.

2022-11-04 13:14 UTC, chrkli22 commented on modules/PowermeterBSM/lib/sunspec_base.hpp
> +    PointType pointType;
fixed

2022-11-04 13:17 UTC, chrkli22 commented on modules/PowermeterBSM/manifest.json
> +			"description": "wakup interval of watchdog in seconds (default 60 seconds).",
This would sound like "wake up the module", but this is paramter how the module works.

2022-11-04 13:18 UTC, chrkli22 commented on modules/PowermeterBSM/manifest.json
> +			"min_connections": 1,
Yes, valid point. I did not find a way to make this optional.

2022-11-04 13:19 UTC, chrkli22 commented on modules/PowermeterBSM/CMakeLists.txt
> +target_link_libraries( sunspec_framework_object_lib PUBLIC everest::framework )
cleaned that up.

2022-11-04 13:19 UTC, chrkli22 commented on modules/PowermeterBSM/CMakeLists.txt
> +    GTest::gtest_main
building tests now is optional.

2022-11-04 13:20 UTC, chrkli22 commented on modules/PowermeterBSM/lib/transport.hpp
> +    inline everest::connection::RTUConnection& rtu_connection() {
I changed it. I learned that the meaning of "inline" has changed a bit.

2022-11-04 13:22 UTC, chrkli22 commented on modules/PowermeterBSM/lib/transport.cpp
> +    std::size_t counter = 10;
refactored to const values, but not in extra headers, since these values only make sense there.

2022-11-04 13:24 UTC, chrkli22 commented on modules/PowermeterBSM/lib/base_types.hpp
> +Types::ModbusRegisterAddress operator"" _mra(unsigned long long int v);
https://en.cppreference.com/w/cpp/language/user_literal

2022-11-04 13:26 UTC, chrkli22 commented on modules/PowermeterBSM/lib/known_model.hpp
> +namespace KnownModel {
added a comment that hopefully explains this.

2022-11-09 07:50 UTC, SebaLukas commented on CMakeLists.txt
> +    include("${everest-cmake_SOURCE_DIR}/everest-cmake-coes/Powermetefig.cmake")
Revert back to everest-cmake-config.cmake

2022-11-09 07:52 UTC, SebaLukas commented on cmake/assets/logging.ini
> +# Filter="%Severity% >= DEBG"
Please delete comments and revert Filter back without contains bsm_power_meter

2022-11-09 07:55 UTC, SebaLukas commented on config/config-sil.json
> +            "serial_device" : "/dev/ttyUSB0"
A SIL with a HW dependency is not a SIL. Perhaps a little BSM_Simulator is better here like the slac or imd simulator

2022-11-09 07:56 UTC, SebaLukas commented on interfaces/sunspec_ac_meter.json
> +    "description": "get sunspec ac meter measurement",
Get

2022-11-09 07:56 UTC, SebaLukas commented on interfaces/sunspec_ac_meter.json
> +                "description": "sunspec ac meter model",
Sunspec

2022-11-09 08:29 UTC, SebaLukas commented
- SIL is not running because of missing HW -> SIL should work without HW 
- Codacy issues
- The descriptions are not always capitalized

2022-11-22 09:12 UTC, SebaLukas commented
There are still a few json files. Do they have to stay in?

2022-11-23 07:17 UTC, closed without merging