Add high level communication module of chargebyte
EVerest/everest-core pull request #190
Opened 2023-03-07 16:48 UTC by mooraby

This pull request adds a new module named EvseV2G. This module provides a C/C++ based implementation of the ISO 15118/DIN 70121 EIM standard for charging stations. It implements the “ISO15118_charger” interface of the EVerest framework. This module is contributed by chargebyte GmbH.

Implemented features:

Support of ISO 15118-2 EIM AC and DC
Support of DIN 70121 EIM
Prototypical implementation of ISO 15118-2 PnC

2023-03-13 10:09 UTC, SebaLukas commented on modules/EvseV2G/EvseV2G.cpp
> +    dlog(DLOG_LEVEL_INFO, "Starting SDP responder");
Debug instead of log

2023-03-14 08:44 UTC, corneliusclaussen commented on modules/EvseV2G/iso_server.cpp
> +#include <json-c/json.h>
Adds a dependency to libjson-c, but does not use it. Suggested to remove include

2023-03-14 12:55 UTC, SebaLukas requested changes
I went over the code roughly and didn't find anything big. Please have a look at my comments.
There are still a few codacy errors. But they should be relatively easy to fix.

The libevent-devel and the json-c (if it is really needed) package was missing. Please add these also in the Readme.md.

2023-03-14 12:55 UTC, SebaLukas commented on modules/EvseV2G/v2g_server.cpp
> +static types::iso15118_charger::V2G_Message_ID get_V2G_Message_ID(enum V2gMsgTypeId v2g_msg, bool is_req) {
DIN specific messages are missing. E.g. ContractAuthentication

2023-03-14 12:55 UTC, SebaLukas commented on README.md
> +
No longer relevant when openv2g is used as fork

2023-03-21 15:23 UTC, SebaLukas requested changes
I found three more things that should be changed.
After the changes then also please do a squash :)

2023-03-21 15:23 UTC, SebaLukas commented on modules/EvseV2G/charger/ISO15118_chargerImpl.cpp
> +    }
Where is the else case?

2023-03-21 15:23 UTC, SebaLukas commented on modules/EvseV2G/CMakeLists.txt
> +        din_server.cpp
Please change to:
```cpp
"v2g_ctx.cpp"
"log.cpp"
"sdp.cpp"
"connection.cpp"
"tools.cpp"
"v2g_server.cpp"
"iso_server.cpp"
"din_server.cpp"
```

2023-03-21 15:23 UTC, SebaLukas commented on dependencies.yaml
> +  git: https://github.com/chargebyte/mbedtls.git
Please change to:
`git: https://github.com/EVerest/ext-mbedtls.git`

This is a fork from your mbedtls repo.

2023-03-21 15:25 UTC, SebaLukas commented
I will look for the codacy issues in parallel. And try to fix them.

2023-03-21 15:32 UTC, SebaLukas commented on modules/EvseV2G/charger/ISO15118_chargerImpl.cpp
> +    }
Alright :thumbsup:

2023-03-22 07:53 UTC, SebaLukas requested changes
Codacy issues fixes

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/connection.cpp
> +        static_cast<char*>(malloc(max(strlen(DEFAULT_PKI_PATH), strlen(DEFAULT_KEY_PATH)) + MAX_FILE_NAME_LENGTH));
```cpp
static_cast<char*>(malloc(max(std::string(DEFAULT_PKI_PATH).size(), std::string(DEFAULT_KEY_PATH).size()) + MAX_FILE_NAME_LENGTH));
```

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/connection.cpp
> +        if ((dir->d_type == DT_DIR) && (strlen(dir->d_name) && isdigit((int)dir->d_name[0])) &&
```cpp
if ((dir->d_type == DT_DIR) && (std::string(dir->d_name).size() && isdigit((int)dir->d_name[0])) &&
```

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/connection.cpp
> +    struct v2g_context* ctx = (struct v2g_context*)data;
```cpp
struct v2g_context* ctx =  static_cast<v2g_context*>(data);
```

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/iso_server.cpp
> +                              (unsigned char*)v2g_payment_details_req->ContractSignatureCertChain.Certificate.bytes,
`v2g_payment_details_req->ContractSignatureCertChain.Certificate.bytes` without casting

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/iso_server.cpp
> +                mbedtls_base64_encode(NULL, 0, &olen, (unsigned char*)subCertTmp->Certificate.array[idx].bytes,
`mbedtls_base64_encode(NULL, 0, &olen, subCertTmp->Certificate.array[idx].bytes,`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/iso_server.cpp
> +                base64Buffer = (unsigned char*)malloc(olen);
`base64Buffer = static_cast<unsigned char*>(malloc(olen));`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/iso_server.cpp
> +                                            (unsigned char*)subCertTmp->Certificate.array[idx].bytes,
`subCertTmp->Certificate.array[idx].bytes,` without casting

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/iso_server.cpp
> +    dlog(DLOG_LEVEL_INFO, "SessionSetupReq.EVCCID: %s", strlen(buffer) ? buffer : "(zero length provided)");
`dlog(DLOG_LEVEL_INFO, "SessionSetupReq.EVCCID: %s", std::string(buffer).size() ? buffer : "(zero length provided)");`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/iso_server.cpp
> +        if ((strlen(cert_emaid) != req->eMAID.charactersLen) ||
`if ((std::string(cert_emaid).size() != req->eMAID.charactersLen) ||`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/iso_server.cpp
> +            mbedtls_strerror(err, strerr, strlen(strerr));
`mbedtls_strerror(err, strerr, std::string(strerr).size());`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/iso_server.cpp
> +                                       strlen(conn->ctx->evse_v2g_data.cert_install_res_b64_buffer))) != 0) {
`std::string(conn->ctx->evse_v2g_data.cert_install_res_b64_buffer).size())) != 0) {`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/log.cpp
> +        size_t formatlen = strlen(format);
`size_t formatlen = std::string(format).size();`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/tools.cpp
> +#include <stdio.h>
Adding here `#include <string>`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/tools.cpp
> +    uint8_t file_name_identifier_len = strlen(file_name_identifier);
`uint8_t file_name_identifier_len = std::string(file_name_identifier).size();`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/tools.cpp
> +            }
```cpp
if ((std::string(dir->d_name).size() > (file_name_identifier_len)) && /* Plus one for the numbering */
    (strncmp(file_name_identifier, dir->d_name, file_name_identifier_len) == 0) &&
    (file_name_len > std::string(dir->d_name).size())) {
    strncpy(file_name, dir->d_name, std::string(dir->d_name).size() + 1);
    break;
}
```

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/tools.cpp
> +    uint8_t suffix_len = strlen(suffix);
```cpp
uint8_t prefix_len = std::string(prefix).size();
uint8_t suffix_len = std::string(suffix).size();
```

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/tools.cpp
> +            if ((strlen(dir->d_name) > (prefix_len + suffix_len + 1)) && /* Plus one for the numbering */
`if ((std::string(dir->d_name).size() > (prefix_len + suffix_len + 1)) && /* Plus one for the numbering */`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/tools.cpp
> +                        if (MAX_FILE_NAME_LENGTH >= strlen(dir->d_name)) {
`if (MAX_FILE_NAME_LENGTH >= std::string(dir->d_name).size()) {`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/v2g_ctx.cpp
> +            static_cast<uint16_t>(strlen((const char*)ctx->evse_v2g_data.evse_id.bytes));
```cpp
std::string evse_id = std::string("DE*CBY*ETE1*234");
strcpy(reinterpret_cast<char*>(ctx->evse_v2g_data.evse_id.bytes), evse_id.data());
ctx->evse_v2g_data.evse_id.bytesLen = evse_id.size();
```

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/v2g_ctx.cpp
> +                strlen(parameterSet->Parameter.array[0].Name.characters);
`std::string(parameterSet->Parameter.array[0].Name.characters).size();`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/v2g_ctx.cpp
> +                strlen(parameterSet->Parameter.array[0].stringValue.characters);
`std::string(parameterSet->Parameter.array[0].stringValue.characters).size();`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/v2g_ctx.cpp
> +                strlen(parameterSet->Parameter.array[0].Name.characters);
`std::string(parameterSet->Parameter.array[0].Name.characters).size();`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/v2g_ctx.cpp
> +                strlen(parameterSet->Parameter.array[0].stringValue.characters);
`std::string(parameterSet->Parameter.array[0].stringValue.characters).size();`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/v2g_server.cpp
> +        if (strlen(hex) == 1)
`if (std::string(hex).size() == 1)`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/v2g_server.cpp
> +    mbedtls_base64_encode(NULL, 0, &base64_buffer_len, (unsigned char*)conn->buffer,
Casting is not needed

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/v2g_server.cpp
> +    v2gMessage.V2G_Message_EXI_Base64 = std::string((const char*)base64_buffer, base64_buffer_len);
`v2gMessage.V2G_Message_EXI_Base64 = std::string(reinterpret_cast<char const*>(base64_buffer), base64_buffer_len);`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/v2g_server.cpp
> +    conn->buffer = (uint8_t*)malloc(DEFAULT_BUFFER_SIZE);
`conn->buffer = static_cast<uint8_t*>(malloc(DEFAULT_BUFFER_SIZE));`

2023-03-22 07:53 UTC, SebaLukas commented on modules/EvseV2G/v2g_server.cpp
> +                usleep((MAX_RES_TIME - time_to_conf_res) * 1000);
```cpp
std::this_thread::sleep_for(
    std::chrono::microseconds((MAX_RES_TIME - time_to_conf_res) * 1000));
```

2023-03-22 15:12 UTC, SebaLukas commented
Please use squash and merge :)

2023-03-22 16:44 UTC, merged