New energy manager
EVerest/everest-core pull request #192
Opened 2023-03-16 15:49 UTC by corneliusclaussen

It creates an energy market and each EvseManager now has a broker that buys/sells energy on behalf of the EvseManager. This allows to simply implement new charging strategies.
This commit includes the basic architecture as well as the default FastCharging broker.

Supports:

- AC and DC (also mixed environments)
- Limited bidirectional charging
- schedules for import and export of energy
- prepared for OCPP smart charging compatibility
- enforcing external (schedule) limits at each node of the tree

Known limits:
- It does not use powermeters yet, hence does not wait for one evse to power down before the other powers up
- Bidirectional charging is supported with a hack config option for ISO-2 and DIN SPEC. It needs to be modified for ISO-20.
- Smart charging goals not supported yet (pricing, ...)

2023-03-20 14:01 UTC, hikinggrass requested changes

2023-03-21 13:28 UTC, corneliusclaussen commented on interfaces/energy.yaml
>          description: UUID of node that this limit applies to
fixed

2023-03-21 13:35 UTC, corneliusclaussen commented on interfaces/energy.yaml
> +    $ref: /energy#/EnergyFlowRequest
No new line at end of ./GenericPowermeter/models/test_dummy.yaml
No new line at end of ./GenericPowermeter/models/template.yaml
No new line at end of ./PacketSniffer/cmake/FindPCAP.cmake

2023-03-21 13:36 UTC, corneliusclaussen commented on interfaces/energy.yaml
> +    $ref: /energy#/EnergyFlowRequest
All that relate to this PR have a line ending at the end of file now.

2023-03-21 13:37 UTC, corneliusclaussen commented on interfaces/external_energy_limits.yaml
> +        description: UUID of node that this limit applies to
fixed

2023-03-21 13:43 UTC, corneliusclaussen commented on modules/EnergyManager/BrokerFastCharging.cpp
> +        EVLOG_error << "import and export offer do not have the same size!";
fixed

2023-03-21 13:46 UTC, corneliusclaussen commented on modules/EvseManager/evse/evse_managerImpl.cpp
> +    mod->mqtt.subscribe(
we should, but let's do it in a seperate pull request as it touches much more then just energy management

2023-03-21 13:50 UTC, corneliusclaussen commented on modules/EvseManager/manifest.yaml
> +  max_current_import:
fixed

2023-03-21 13:59 UTC, corneliusclaussen commented on modules/JsDCSupplySimulator/index.js
will fix in a seperate commit

2023-03-21 14:31 UTC, corneliusclaussen commented on modules/EvseManager/energy_grid/energyImpl.cpp
> +                    s == Charger::EvseState::PrepareCharging || s == Charger::EvseState::WaitingForEnergy ||
fixed

2023-03-21 14:32 UTC, corneliusclaussen commented on modules/EvseManager/energy_grid/energyImpl.cpp
> +                        e.limits_to_root.ac_min_current_A = hw_caps.max_current_A_import;
fixed

2023-03-21 14:33 UTC, corneliusclaussen commented on modules/EvseManager/EvseManager.cpp
>                  // Some power supplies don't really like 0 current limits
no, just a left over

2023-03-21 14:33 UTC, corneliusclaussen commented on modules/EnergyManager/Market.cpp
> +    return _parent == NULL;
fixed

2023-03-21 14:33 UTC, corneliusclaussen commented on modules/EnergyManager/Market.hpp
> +           Market* __parent = NULL);
fixed

2023-03-21 14:35 UTC, corneliusclaussen commented on modules/EnergyManager/EnergyManager.cpp
> +    int timeout = 100;
fixed

2023-03-21 14:40 UTC, corneliusclaussen commented on modules/EnergyManager/BrokerFastCharging.cpp
> +bool BrokerFastCharging::buy_ampere_import(int i, float a, bool allow_less) {
fixed

2023-03-21 14:48 UTC, corneliusclaussen commented on modules/EnergyManager/EnergyManager.cpp
> +                                      it.limits_root_side.value().ac_max_current_A.value_or(-9999),
removed 9999 constant, added a proper debug string

2023-03-21 16:50 UTC, hikinggrass commented on modules/EnergyManager/BrokerFastCharging.hpp
In this header a few "i" and "a" parameter names are still left, fixed already in the cpp file

2023-03-21 17:15 UTC, hikinggrass approved these changes

2023-03-21 19:18 UTC, merged