Feature/error handling
EVerest/everest-core pull request #284
Opened 2023-07-13 10:29 UTC by andistorm

2023-09-18 06:21 UTC, corneliusclaussen commented on modules/examples/ExampleUser/example_user/example_userImpl.hpp
> +    boost::uuids::uuid received_error;
I think we should define a new type here, Everest::ErrorHandle or similar instead of using boost::uuid directly

2023-09-26 09:36 UTC, andistorm commented on interfaces/example.yaml
> +  - example/ExampleErrorB
I am going to adapt it

2023-10-18 12:00 UTC, andistorm commented
depends on https://github.com/EVerest/everest-utils/pull/59
depends on https://github.com/EVerest/everest-framework/pull/92

2023-10-20 11:29 UTC, hikinggrass requested changes

2023-10-20 11:29 UTC, hikinggrass commented on cmake/everest-generate.cmake
> +            # _ev_convert_refs(${MODULE_PATH}/manifest.yaml modules/${MODULE_NAME})
remove

2023-11-02 12:46 UTC, andistorm commented on config/config-example.yaml
> +  logging_config_file: /home/andreas/everest-logging-config.conf
```suggestion
```

2023-11-02 12:48 UTC, andistorm commented
Do not megre beofre updating dependencies.yaml

2023-11-02 17:24 UTC, hikinggrass commented on interfaces/example.yaml
> +  # - reference: /errors/example#/ExampleErrorA
remove comment?

2023-11-02 17:24 UTC, hikinggrass approved these changes

2023-11-03 09:18 UTC, merged