API: prevent iterator invalidation
EVerest/everest-core pull request #361
Opened 2023-09-27 11:09 UTC by dorezyuk

When defining more than 1 container the API node crahes.

The cause it that as the vector grows its iterators may get invalidated. The std::list offers stable iterators. 
The overhead between the vector and list in this case should not affect us since we're never iterating over `info` or `hw_capabilities_json`.

2023-10-04 10:16 UTC, corneliusclaussen commented
Could you sign off the commit (see DCO guidelines from the Linux foundation)?

2023-10-05 14:28 UTC, a-w50 requested changes
Hi @dorezyuk 

thanks for this find, quite some "tricky" bug ...
Please fix the clang format

2023-10-05 14:28 UTC, a-w50 commented on modules/API/API.hpp
> +#include <list>
to make clang-format happy, the includes need to be sorted alphabetically, so `<list>` needs to be above `<memory>`

2023-10-05 14:28 UTC, a-w50 commented on modules/API/API.hpp
> +    // ensure that our iterators don't get invalidated.
I wouldn't leave this command here, this should be evident for this piece of code (it could also be moved into the commit message)

2023-11-01 21:15 UTC, a-w50 approved these changes

2023-11-01 21:16 UTC, merged