Pg add security to evsev2g
EVerest/everest-core pull request #394
Opened 2023-10-20 13:57 UTC by AssemblyJohn

2023-10-20 15:06 UTC, corneliusclaussen requested changes
Build in the CI should be fixed before merging

2023-10-20 15:06 UTC, corneliusclaussen commented on modules/EvseV2G/manifest.yaml
> +    max_connections: 1
min and max could be removed here, the default is always exaclty one

2023-10-25 07:45 UTC, SebaLukas requested changes
Basically, I think the changes are good :+1: 
Since the requirement of EvseSecurity is not optional, please extend it for all config.yaml files that use EvseV2G. E.g. config-sil-dc, config-sil-two-evse etc.

2023-10-31 11:27 UTC, Pietfried approved these changes

2023-10-31 12:50 UTC, SebaLukas approved these changes
:+1:

2023-10-31 13:34 UTC, corneliusclaussen approved these changes

2023-10-31 13:41 UTC, merged