Add SignedMeterValue type powermeter types
EVerest/everest-core pull request #461
Opened 2023-11-30 22:09 UTC by hikinggrass

This allows the encapsulation of additionaly metadata like the signing method, encoding method or the public key next to the signed meter data

2023-12-07 12:58 UTC, valentin-dimov submitted a review, later dismissed
We also need to adjust the `TransactionFinished` in the `evse_manager` interface to use the `SignedMeterValue` type.

2023-12-07 12:58 UTC, valentin-dimov commented on types/powermeter.yaml
> +        description: Base64 encoded signed meter data
Does this necessarily have to be Base64? I think we can keep things more generic here, since we have `encoding_method` below anyway...

2023-12-11 09:27 UTC, valentin-dimov reviewed
Looks good, only some minor questions left

2023-12-11 09:27 UTC, valentin-dimov commented on types/evse_manager.yaml
> +        description: The signed meter value report of the started transation
```suggestion
        description: The signed meter value report of the started transaction
```

2023-12-11 09:27 UTC, valentin-dimov commented on types/evse_manager.yaml
> +        description: The signed meter value report of the stopped transation
```suggestion
        description: The signed meter value report of the stopped transaction
```

2023-12-11 09:27 UTC, valentin-dimov commented on types/powermeter.yaml
> +        $ref: /units_signed#/SignedMeterValue
Why do we have this here, if we already have the signed variant of each unit above? If this is to support powermeters that sign the whole package at once, then we should explain that in the description.

2024-02-02 22:00 UTC, golovasteek commented on types/units_signed.yaml
> +        $ref: /units_signed#/SignedMeterValue
I'm curious, are there any meters out there that provide signed Voltage readings?

Same for frequency and other detailed measurements, every signed separtely.

2024-02-09 11:00 UTC, hikinggrass commented
> Looking forward for this to be applied. Preferrably reduced to "SignedMeterValues" only.
> 
> Can we push this PR forward? So that further work on the power meters can be based on it already?

Yes, I'll rebase it and will try to restructure it a bit

2024-02-20 07:53 UTC, Pietfried approved these changes

2024-02-22 15:51 UTC, Pietfried requested changes
Requested changes do not fix changes of this PR, but fix bugs that have been introduced earlier and I'd like to see fixed in this PR

2024-02-22 15:51 UTC, Pietfried commented on modules/OCPP201/OCPP201.cpp
>              sampled_value.value = power_meter.energy_Wh_import.L1.value();
```suggestion
            sampled_value.value = power_meter.energy_Wh_export.L1.value();
```

2024-02-22 15:51 UTC, Pietfried commented on modules/OCPP201/OCPP201.cpp
>              sampled_value.value = power_meter.energy_Wh_import.L2.value();
```suggestion
            sampled_value.value = power_meter.energy_Wh_export.L2.value();
```

2024-02-22 15:51 UTC, Pietfried commented on modules/OCPP201/OCPP201.cpp
>              sampled_value.value = power_meter.energy_Wh_import.L3.value();
```suggestion
            sampled_value.value = power_meter.energy_Wh_export.L3.value();
```

2024-02-22 15:51 UTC, Pietfried commented on modules/OCPP201/OCPP201.cpp
>              sampled_value.value = power_meter.energy_Wh_import.L1.value();
```suggestion
            sampled_value.value = power_meter.power_W.L1.value();
```

2024-02-22 15:51 UTC, Pietfried commented on modules/OCPP201/OCPP201.cpp
>              sampled_value.value = power_meter.energy_Wh_import.L2.value();
```suggestion
            sampled_value.value = power_meter.power_W.L2.value();
```

2024-02-22 15:51 UTC, Pietfried commented on modules/OCPP201/OCPP201.cpp
>              sampled_value.value = power_meter.energy_Wh_import.L3.value();
```suggestion
            sampled_value.value = power_meter.power_W.L3.value();
```

2024-02-22 15:51 UTC, Pietfried commented on modules/OCPP201/OCPP201.cpp
>              sampled_value.value = power_meter.energy_Wh_import.L1.value();
```suggestion
            sampled_value.value = power_meter.VAR.value().L1.value();
```

2024-02-22 15:51 UTC, Pietfried commented on modules/OCPP201/OCPP201.cpp
>              sampled_value.value = power_meter.energy_Wh_import.L2.value();
```suggestion
            sampled_value.value = power_meter.VAR.value().L2.value();
```

2024-02-22 15:51 UTC, Pietfried commented on modules/OCPP201/OCPP201.cpp
>              sampled_value.value = power_meter.energy_Wh_import.L3.value();
```suggestion
            sampled_value.value = power_meter.VAR.value().L3.value();
```

2024-02-23 13:54 UTC, merged