Feature/reservations
EVerest/everest-core pull request #48
Opened 2022-05-09 13:40 UTC by chGoodchild

Added OCPP reservations without any caching of reservations in the OCPP charge point:
* Switched from `std::chrono::system_clock()` to `date::utc_clock()` to avoid discrepancies with absolute time points.
* Reservations are only stored by EVerest.

2022-05-09 14:09 UTC, hikinggrass requested changes

2022-05-09 14:09 UTC, hikinggrass commented on modules/EvseManager/EvseManager.cpp
> +    EVLOG(critical) << "valid_until: " << valid_until;
Remove critical log messages

2022-05-09 14:09 UTC, hikinggrass commented on modules/EvseManager/EvseManager.cpp
> +    if (!reserved)
if block { }

2022-05-09 14:09 UTC, hikinggrass commented on modules/EvseManager/EvseManager.cpp
> +    #ifndef NDEBUG
Could these messages become "debug" messages?

2022-05-09 14:09 UTC, hikinggrass commented on modules/EvseManager/EvseManager.cpp
> +    if (!reserved)
if block { }

2022-05-09 14:09 UTC, hikinggrass commented on modules/OCPP/OCPP.hpp
> +    std::map<int32_t, int32_t> ResConnMap;
I think we should continue using snake case for consistency here. eg. res_conn_map and res_state_map. Maybe drop the _map postfix as well

2022-05-09 14:09 UTC, hikinggrass commented on modules/YetiDriver/yeti_comms/CMakeLists.txt
> +)
Missing newline at end of file

2022-05-09 14:09 UTC, hikinggrass commented on run_sil-ocpp-complete-fixture.sh
> +#!/bin/sh
Remove, seems redundant
How is this file different from run_sil-ocpp-complete.sh other than using another directory level?

2022-05-09 14:09 UTC, hikinggrass commented on tests/test_reserve_now.py
> +from paho.mqtt import client as mqtt_client
I'm not sure about including this just yet, things especially with python based testing will change quite a bit in the near future. I would rather remove this for now and introduce it when all the pieces are in place

2022-05-09 20:12 UTC, chGoodchild commented
It runs again, but I have unsigned commits before Kai's commit: fc52f57162cc8045d0aa4ae73ce43a081ecbd183
I will fix this by: 
* resetting the head to this commit: fced91f8104ec8910aeabcb37f55c45a590b42e7
* signing my commits
* creating a new branch with the signed commits
* cherry picking Kai's commits into my new branch
* cherry picking my latest commits into the new branch
* signing my latest commits
* and overwriting this branch

Then it should be ready to merge :)

2022-05-16 13:41 UTC, hikinggrass approved these changes

2022-05-16 13:49 UTC, hikinggrass approved these changes

2022-05-16 14:58 UTC, merged