Various custom data extensions
EVerest/everest-core pull request #605
Opened 2024-03-26 20:21 UTC by hikinggrass

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-04-10 10:27 UTC, Pietfried requested changes
Type and interface changes look good.

I would suggest to move all the conversions in OCPP201.cpp and ocpp_data_transferImpl.cpp to the dedicated conversions.hpp and .cpp

2024-04-10 10:27 UTC, Pietfried commented on modules/OCPP201/data_transfer/ocpp_data_transferImpl.cpp
> +    }
This could be moved to the conversions.hpp and .cpp

2024-04-10 10:27 UTC, Pietfried commented on modules/OCPP201/data_transfer/ocpp_data_transferImpl.cpp
> +    }
This could be moved to the conversions.hpp and .cpp

2024-04-10 10:27 UTC, Pietfried commented on modules/OCPP201/OCPP201.cpp
> +            }
Same here: This could be moved to the conversions.hpp and .cpp

2024-04-10 10:27 UTC, Pietfried commented on modules/OCPP201/OCPP201.cpp
> +            }
Same here: This could be moved to the conversions.hpp and .cpp

2024-04-10 10:27 UTC, Pietfried commented on modules/OCPP201/data_transfer/ocpp_data_transferImpl.cpp
> +        ocpp_request.data = json::parse(request.data.value());
id suggest to catch the exception for all `json::parse` in case the data could not be parsed

2024-04-12 09:21 UTC, Pietfried approved these changes
update of dependencies.yaml requried once https://github.com/EVerest/libocpp/pull/541 is merged

2024-04-12 13:43 UTC, dorezyuk approved these changes

2024-04-12 13:47 UTC, merged