Add version information
EVerest/everest-core pull request #622
Opened 2024-04-04 17:05 UTC by hikinggrass

## Describe your changes
Uses everest-cmake 0.3 to generate version information that can be parsed and shown by the EVerest manager on startup

## Issue ticket number and link

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-06-14 16:11 UTC, andistorm requested changes

2024-06-14 16:11 UTC, andistorm commented on .github/workflows/build_and_test.yaml
> +  BUILD_KIT_IMAGE: ghcr.io/everest/build-kit-alpine:rc1.1.4
Before merging:
```suggestion
  BUILD_KIT_IMAGE: ghcr.io/everest/build-kit-alpine:v1.1.4
```

2024-06-15 07:21 UTC, hikinggrass commented on .github/workflows/build_and_test.yaml
> +  BUILD_KIT_IMAGE: ghcr.io/everest/build-kit-alpine:rc1.1.4
fixed

2024-06-15 07:24 UTC, corneliusclaussen approved these changes

2024-06-15 11:32 UTC, Pietfried approved these changes

2024-06-16 10:45 UTC, andistorm approved these changes

2024-06-17 12:34 UTC, merged