Refactored OCMF powermeter transaction handling
EVerest/everest-core pull request #640
Opened 2024-04-18 18:09 UTC by Pietfried

## Describe your changes
Refactored OCMF powermeter transaction handling:
* Powermeter interface now contains proper user identification arguments (IS, IT, IF, IT, ID) to start the transaction
* Refactored EvseManager and LemDCBM400600 modules to address the changed types
* Added module config params for LemDCBM400600 : cable_id, tariff_id
* Fixed test cases in LemDCBM400600 due to changes made

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-04-19 05:28 UTC, a-w50 requested changes
Missing some documentation about why for ex. `cable_id` and `tariff_id` have been removed from the powermeter type and are now only local config options for the LEM powermeter

2024-04-19 05:28 UTC, a-w50 commented on modules/EvseManager/Charger.cpp
> +#include <utils.hpp>
`#include "utils.hpp"`, try to seperate includes by their scope ...

2024-04-19 05:28 UTC, a-w50 commented on modules/EvseManager/Charger.cpp
> +        std::nullopt};
This is hard to read, might help to have comments or set each field by hand - also very error prone

2024-04-19 06:09 UTC, a-w50 commented on modules/EvseManager/utils.hpp
> +    default:
in order for static analysis being able to see missing enum types in a switch, you shouldn't have a `default` case.  Therefor in most situations it is better practice to leave out the `default` case, just do a return of the default value after the switch

2024-04-19 11:27 UTC, Pietfried commented
> Missing some documentation about why for ex. `cable_id` and `tariff_id` have been removed from the powermeter type and are now only local config options for the LEM powermeter

The `cable_id` is no OCMF parameter but it is specific to the LEM powermeter and shall therefore not be an argument within the `TransactionReq` type. A `tariff_id` is also no OCMF parameter (but Tariff Text (TT) is) and in the LEM communication protocol it is unclear how this parameter shall be set. This might require further changes in the LEM module, but it doesnt belong to the `TransactionReq` type.

2024-04-19 19:35 UTC, a-w50 commented
> > Missing some documentation about why for ex. `cable_id` and `tariff_id` have been removed from the powermeter type and are now only local config options for the LEM powermeter
> 
> The `cable_id` is no OCMF parameter but it is specific to the LEM powermeter and shall therefore not be an argument within the `TransactionReq` type. A `tariff_id` is also no OCMF parameter (but Tariff Text (TT) is) and in the LEM communication protocol it is unclear how this parameter shall be set. This might require further changes in the LEM module, but it doesnt belong to the `TransactionReq` type.

That is exactly what I would like to see in the commit or PR message, so that we're able to reason about why those changes happened.

2024-04-19 19:40 UTC, a-w50 approved these changes

2024-04-22 07:53 UTC, SirVer commented on modules/RsIskraMeter/src/main.rs
> +            identification_type: "ISO14443",
This should not compile. Did you try compiling with Rust support? there is at least a `.to_string()` missing here.

2024-04-22 07:56 UTC, Pietfried commented
> @Pietfried The MR description explains the "what" happened, but not the "why", please extend, i.e. I have a similar question than @a-w50.

Hi @SirVer , this response to @a-w50 request explains "why" the changes are required: https://github.com/EVerest/everest-core/pull/640#issuecomment-2067176131 .

Please have a look at the Rust build, which is currently failing. It looks like `minItems` and `maxItems` keywords are not supported in the rust part.

2024-04-22 08:02 UTC, SirVer commented on types/powermeter.yaml
> +          maxItems: 4
I think they should be, yes. If not it is a bug that should be fixed. @dorezyuk, can you make sure and fix this MR too?

2024-04-22 08:03 UTC, SirVer commented
> Hi @SirVer , this response to @a-w50 request explains "why" the changes are required: https://github.com/EVerest/everest-core/pull/640#issuecomment-2066376028 .

Yes, I saw that @Pietfried. My statement was more that this should go into the MR description, because it is important context for posterity and should not be buried in the discussion.

2024-04-22 08:18 UTC, dorezyuk commented on types/powermeter.yaml
> +          maxItems: 4
@Pietfried Your indentation level is one too deep - you basically say right now "an array of arbitary length with strings between 0 and 4  chars" `(std::vector<std::array<char, 4>>)`. If this is what you want then you need to rename the `minItems` and `maxItems` to `minLength` and `maxLength`.

If you want to day an array between 0 and 4 with any string, then you need to move the `maxItems` and `minItems` one up

```yaml
type:array
minItems: 0
maxItems: 1
items:
  type:string
```

2024-04-22 08:36 UTC, Pietfried commented on types/powermeter.yaml
> +          maxItems: 4
good catch, thanks!

2024-04-22 12:43 UTC, dorezyuk commented on modules/RsIskraMeter/src/main.rs
> +                identification_status: generated::types::powermeter::OCMFUserIdentificationStatus::ASSIGNED,
nice great job with fixing. There is a generated::types::powermeter include block at the top of the file. Lets add OCMFIdentificationType to it so we can write here just OCMFIdentificationType::ISO14443 and so on

2024-04-22 15:58 UTC, dorezyuk commented on modules/RsIskraMeter/src/main.rs
> +                identification_data: Some(String::new()),
I think this (and the 2 fields below) could also just be `None`

2024-04-23 06:54 UTC, dorezyuk approved these changes

2024-04-23 08:14 UTC, SirVer approved these changes
Great, thanks for addressing the boolean. The resulting code is much better I think!

2024-04-29 08:17 UTC, SebaLukas approved these changes
:+1:

2024-04-30 08:20 UTC, a-w50 commented
> @Pietfried The MR description explains the "what" happened, but not the "why", please extend, i.e. I have a similar question than @a-w50.

Exactly, that's what I was trying to say.

2024-05-02 07:06 UTC, corneliusclaussen approved these changes

2024-05-02 08:58 UTC, merged