Export Logger.ini
EVerest/everest-core pull request #737
Opened 2024-06-24 07:40 UTC by dorezyuk

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-06-24 07:56 UTC, SirVer approved these changes

2024-06-24 08:04 UTC, hikinggrass commented
@dorezyuk your commit is missing a sign-off before we can merge it

2024-06-26 11:56 UTC, corneliusclaussen approved these changes

2024-06-26 12:28 UTC, corneliusclaussen commented
@golovasteek your review is missing here

2024-07-09 07:48 UTC, corneliusclaussen requested changes

2024-07-09 07:48 UTC, corneliusclaussen commented on interfaces/powermeter.yaml
> +  public_key:
In the mean time this was added in core as well but with a different name: public_key_ocmf

2024-07-09 13:32 UTC, corneliusclaussen approved these changes

2024-07-09 14:06 UTC, merged