Feature/evsemanager ocpp errorhandling
EVerest/everest-core pull request #764
Opened 2024-07-05 07:45 UTC by corneliusclaussen

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-07-25 11:28 UTC, Pietfried commented on modules/OCPP/OCPP.cpp
> +            // TODO: Report correct evse_id once Error type includes it
Remove

2024-07-25 11:28 UTC, Pietfried commented on modules/OCPP/OCPP.cpp
> +            // TODO: Report correct evse_id once Error type includes it
Remove

2024-07-25 11:32 UTC, Pietfried commented on modules/OCPP/OCPP.cpp
> +            // intialized
```suggestion
```

2024-07-25 11:42 UTC, Pietfried commented on dependencies.yaml
> +  git_tag: feature/3-tier-model-support
```suggestion
  git_tag: v0.16.0
```

2024-07-30 10:04 UTC, hikinggrass requested changes

2024-07-31 10:41 UTC, Pietfried commented on dependencies.yaml
> +  git_tag: feature/refactor-ocpp16-error-state-machine
```suggestion
  git_tag: 1067cf3ddf27be3a43f8abc519b69da11c4ef921
```

2024-07-31 10:42 UTC, hikinggrass approved these changes

2024-07-31 11:37 UTC, merged