Remove get_hardware_capablities() and 1ph3ph switching support
EVerest/everest-core pull request #769
Opened 2024-07-09 06:27 UTC by corneliusclaussen

Implementation of evse_board_support was simplified a bit. The sync command to get hw capablities on startup is no longer needed as the async publish of capablities is enough. Each BSP implementation module is required to publish its capablities at least once in the ready function. It may publish it later on to update the values e.g. for thermal derating.

1ph/3ph switching support during charging with a hyteresis if the 1ph/3ph power ranges overlap (e.g. on 22kW).
Hysteresis only really works if EV and EVSE have the same max current rating, e.g. both 16A See doc.rst for details.

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I have made corresponding changes to the documentation
- [X] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-07-09 14:42 UTC, Pietfried commented on modules/YetiDriver/yetiR1_2.2_firmware.bin
This requires a change here as well
https://github.com/EVerest/everest-core/blob/main/modules/YetiDriver/CMakeLists.txt#L39

2024-07-11 14:00 UTC, corneliusclaussen commented on modules/YetiDriver/yetiR1_2.2_firmware.bin
fixed

2024-07-22 09:31 UTC, Pietfried requested changes
See comments + Lint and Tests are currently failing

2024-07-22 09:31 UTC, Pietfried commented on modules/EvseManager/EvseManager.hpp
> +    std::atomic_int ac_nr_ph_phases_active{0};
`ac_nr_phases_active` ?

2024-07-22 09:31 UTC, Pietfried commented on modules/PhyVersoBSP/connector_1/evse_board_supportImpl.cpp
> -void evse_board_supportImpl::handle_setup(bool& three_phases, bool& has_ventilation, std::string& country_code) {
Looks like you need to publish the caps for connector 1 as well like its done for connector 2

2024-07-25 16:59 UTC, Pietfried approved these changes

2024-07-26 10:13 UTC, merged