Add composed device model storage and everest device model storage.
EVerest/everest-core pull request #846
Opened 2024-09-03 16:34 UTC by maaikez

## Describe your changes

Created composed device model storage and everest device model storage like stated in https://github.com/EVerest/everest-core/tree/doc/config-service/doc/config_service#next-steps-to-adjust-ocpp201-and-libocpp

## Issue ticket number and link

#844 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-09-05 12:20 UTC, Pietfried requested changes
This looks good!

I would like to see at least some parts of [this](https://github.com/EVerest/everest-core/tree/doc/config-service/doc/config_service#next-steps-to-adjust-ocpp201-and-libocpp) documented here as part of the OCPP201 module documentation:
* Class diagram + explaination
* Variable attributes and variable characteristics for externally managed variables
* Sequence of variable access for internally and externally managed variables

2024-09-05 14:53 UTC, maaikez commented
> This looks good!
> 
> I would like to see at least some parts of [this](https://github.com/EVerest/everest-core/tree/doc/config-service/doc/config_service#next-steps-to-adjust-ocpp201-and-libocpp) documented here as part of the OCPP201 module documentation:
> 
>     * Class diagram + explaination
> 
>     * Variable attributes and variable characteristics for externally managed variables
> 
>     * Sequence of variable access for internally and externally managed variables

ok, in doc.rst? Or where else?

2024-09-05 15:05 UTC, Pietfried commented
> > This looks good!
> > I would like to see at least some parts of [this](https://github.com/EVerest/everest-core/tree/doc/config-service/doc/config_service#next-steps-to-adjust-ocpp201-and-libocpp) documented here as part of the OCPP201 module documentation:
> > ```
> > * Class diagram + explaination
> > 
> > * Variable attributes and variable characteristics for externally managed variables
> > 
> > * Sequence of variable access for internally and externally managed variables
> > ```
> 
> ok, in doc.rst? Or where else?

Yep :+1:

2024-09-05 16:15 UTC, maaikez commented
> > > This looks good!
> > > I would like to see at least some parts of [this](https://github.com/EVerest/everest-core/tree/doc/config-service/doc/config_service#next-steps-to-adjust-ocpp201-and-libocpp) documented here as part of the OCPP201 module documentation:
> > > ```
> > > * Class diagram + explaination
> > > 
> > > * Variable attributes and variable characteristics for externally managed variables
> > > 
> > > * Sequence of variable access for internally and externally managed variables
> > > ```
> > 
> > 
> > ok, in doc.rst? Or where else?
> 
> Yep 👍

Ok, added!

2024-09-12 15:48 UTC, maaikez commented
Is there still a change requested?

2024-11-11 16:08 UTC, Pietfried requested changes
lgtm! Requested some documentation changes partially caused by the renaming to `DeviceModelStorageInterface`

2024-11-11 16:08 UTC, Pietfried commented on modules/OCPP201/doc.rst
> +Device Model Implementation this module
```suggestion
Device Model Implementation of this module
```

2024-11-11 16:08 UTC, Pietfried commented on modules/OCPP201/doc.rst
> +* DeviceModelInterface:
DeviceModelStorageInterface

2024-11-11 16:08 UTC, Pietfried commented on modules/OCPP201/doc/sequence_config_service_and_ocpp.puml
> +database ExternalStorage order 50
Looks like 
```suggestion
database DeviceModelStorageSqlite order 40
database EverestDeviceModelStorage order 50
```
would be more appropriate

2024-11-13 19:00 UTC, Pietfried approved these changes

2024-11-13 19:01 UTC, Pietfried commented
:+1: 

please merge https://github.com/EVerest/libocpp/pull/768 and update the `dependencies.yaml` in this PR afterwards

2024-11-14 14:07 UTC, merged