Adding yeti simulator
EVerest/everest-core pull request #862
Opened 2024-09-10 15:58 UTC by MarzellT

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-10-02 10:14 UTC, corneliusclaussen commented on modules/simulation/JsYetiSimulator/index.js
> +      if (mod.current_state === STATE_DISABLED) mod.state = STATE_A;  // TODO: is this a bug?
state F would be better here

2024-10-02 10:15 UTC, corneliusclaussen commented on modules/simulation/JsYetiSimulator/index.js
> +      if (mod.current_state === STATE_DISABLED) mod.state = STATE_A;  // TODO: is this a bug?
Thats ok

2024-10-02 10:17 UTC, corneliusclaussen approved these changes

2024-10-04 08:01 UTC, SebaLukas requested changes
I am divided on the PR. I think that the code basically works, but I find the architecture confusing.

I think that the complete code from the `simulation.hpp` can also be moved and executed in the `YetiSimulator.cpp`.
This saves the many get functions and the module structure would also be like other EVerest modules. And I think that the clarity will not suffer.

I also don't like the large `ModuleState` struct. This could be reduced by moving the code to YetiSimulator.cpp and define the individual variables and structs, such as `PowermeterData` and `SimulationData`directly in the `YetiSimulator` class.

2024-10-13 22:11 UTC, barsnick commented on modules/YetiSimulator/board_support/evse_board_supportImpl.cpp
> +        .connector_type = types::evse_board_support::Connector_type::IEC62196Type2Cable};
Designated initializers are only supported in C++20 and above.

(Also below with `return {.ampacity = Ampacity::None};`.)

2024-10-13 22:39 UTC, a-w50 submitted a review, later dismissed
See my comments in https://github.com/EVerest/everest-core/pull/887#discussion_r1797430249. Not sure why this is another PR.
I created a working example in this branch: https://github.com/EVerest/everest-core/tree/refactor/cleanup_yeti_sim_error

2025-03-10 12:09 UTC, barsnick commented
Shouldn't this be in subdir `modules/simulation` like the previous JS module?

2025-03-13 08:55 UTC, SebaLukas approved these changes
Looking good :+1:

2025-03-14 09:44 UTC, merged