Feature/cost and price display message tests
EVerest/everest-core pull request #975
Opened 2024-11-28 16:34 UTC by maaikez

## Describe your changes

Add python integration tests for california pricing and display message.

## Issue ticket number and link

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-12-04 12:17 UTC, maaikez commented on dependencies.yaml
> +  git_tag: bugfix/meter-value-pricing-trigger
This should be set back to the correct version as soon as it the bugfix (https://github.com/EVerest/libocpp/pull/899) is merged.

2024-12-05 16:18 UTC, Pietfried requested changes
lgtm except a few inline comments

2024-12-05 16:18 UTC, Pietfried commented on tests/ocpp_tests/test_sets/ocpp16/ocpp_compliance_tests.py
These tests should go into a seperate file like california_pricing.py like for ocpp201

2024-12-05 16:18 UTC, Pietfried commented on tests/ocpp_tests/test_sets/ocpp16/ocpp_compliance_tests.py
> +        return adjusted_config
These seem to be defined similar for ocpp16 and ocpp201 so I think they can be moved to some common file and the be imported

2024-12-05 16:18 UTC, Pietfried commented on tests/ocpp_tests/test_sets/ocpp201/california_pricing.py
> +        #                                probe_module_mock_fn)
Can this be removed?

2024-12-16 09:41 UTC, Pietfried commented on tests/ocpp_tests/test_sets/ocpp16/california_pricing_ocpp16.py
you can just use the name `california_pricing.py` for this file since its inside the `ocpp16` directory

2024-12-16 17:12 UTC, merged